config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'components', to: 'pages#components', as: :components
  mount StripeEvent::Engine, at: '/stripe-webhooks'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'payment_made/:id', to:'orders#payment_made', as: :payment_made

  resources :orders, only: [:index, :show, :new, :create, :update] do
    resources :payments, only: [ :new, :create ]
  end
end

app/views/pages/components.html.erb
<div class="container">
  <H1>Components list</H1>
  <H2>buttons</H2>
  <button type="button" class="btn btn-lg rounded btn-flat">Primary</button>
  <button type="button" class="btn btn-lg rounded btn-secondary">Secondary</button>
  <button type="button" class="btn btn-lg rounded btn-success">Success</button>
  <button type="button" class="btn btn-lg rounded btn-danger">Danger</button>
  <button type="button" class="btn btn-lg rounded btn-warning">Warning</button>
  <button type="button" class="btn btn-lg rounded btn-info">Info</button>

  <H3>cards</H3>

  <div class="card-big bg-success" >
    <h4>Lorem, ipsum dolor sit amet consectetur adipisicing elit.</h4>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa a quasi blanditiis facilis deleniti nisi tempore est nemo necessitatibus, possimus officiis iusto iure aliquid magnam modi adipisci rerum earum suscipit!</p>
  </div>
  <br>

  <div class="card-sm bg-success">
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit.</p>
  </div>


  <h3>Search bar</h3>

  <%= simple_form_for :search, url: root_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <input class="form-control string required" type="text" name="search[query]" id="search_query" />
      <button name="button" type="submit" class="btn btn-secondary">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
  <% end %>
</div>

app/views/pages/home.html.erb
<div>
  <div class="main-header" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://images.unsplash.com/photo-1543352634-99a5d50ae78e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1951&q=80);">
    <div class="title-header ">
      <h1 class="text-center">Hungry?</h1>
      <h2 class="text-center mb-4">Order serendipitous meals from the best restaurants</h2><br>
    </div>
    <div class="searchbar-header">
      <%= form_tag new_order_path, method: :get, class: 'form-inline justify-content-center' do %>
        <div class="search-bar-width">
          <%= text_field_tag :search, params[:search], id: "search", placeholder: "Enter your address"%>
        </div>
        <div>
          <%= submit_tag "Order", class:"btn btn-flat-search" %>
        </div>
      <% end %>
    </div>
  </div>
  <%= image_tag "arc.png", class:'w-100 arc'%>
  <%# <div class="cards-container-landing"> %>
  <%# <div id="oval"></div> %>
  <div id="container-who-landing">
    <div class="container-image-landing">
        <h2 class="text-center our-story"> <strong>Our story</strong></h2>
      <%# <%= image_tag "Logofoodini-roulette.png", alt: "Foodini wheel", class: "image-who" %>
    </div>
    <div id="container-text-landing">
      <div class="container-text-landing-1">
        <h4 class="text-wrap">
        Too often, people eat the <strong>same thing</strong>, don’t know what to cook and always end up ordering from the <strong>same places.</strong>
        Foodini is a <strong>unique food delivery</strong> experience to make people discover <strong>new cuisines</strong>.<br><br><strong style="text-center">Sign up</strong> to learn more about us!</h4>
        </h4>
      </div>
      <div class="container-text-landing-2">
         <%# <%= image_tag "meatballs.jpg", class: 'meatballs img-fluid rounded' %>
         <%= image_tag "eating.svg", class: 'eating-picture' %>
      </div>
    </div>
  </div>

  <div id="container-how-landing">
    <h2 class="text-center"><strong>How it works</strong></h2>
    <div class="cards-landing">
      <div class="card-big">
        <%# <img src="https://static.thenounproject.com/png/12638-200.png" alt> %>
        <%= image_tag "location.png", class: 'landing-how-1' %>
        <h4>1. Enter your location</h4>
        <p>Enter your street address or let us find your location.</p>
      </div>
      <div class="card-big">
        <%# <img src="https://static.thenounproject.com/png/2850062-200.png" alt> %>
        <%= image_tag "budget and waiting time.png", class: 'landing-how-2' %>
        <h4>2. Choose budget & waiting time</h4>
        <p>Just fill in a few criteria to make sure you get the most appropriate meal.</p>
      </div>
      <div class="card-big">
        <%# <img src="https://static.thenounproject.com/png/1671260-200.png" alt> %>
        <%= image_tag "feeling lucky or feeling cautious.png", class: 'landing-how-3' %>
        <h4>3. Feeling lucky or feeling cautious?</h4>
        <p>Feeling <strong>lucky </strong>today? A random meal is chosen for you.
        <br>Feeling <strong>cautious</strong>? Get the chance to try again and get a meal that suits you better.</p>
      </div>
      <div class="card-big">
        <%# <img src="https://static.thenounproject.com/png/1331980-200.png" alt> %>
        <%= image_tag "be surprised.png", class: 'landing-how-4' %>
        <h4>4. Be surprised & receive high qualitative meals</h4>
        <p>Pay and get your serendipitous meal delivered at your doorsteps. Bon appétit!</p>
      </div>
    </div>
  </div>

  <div class="testimonial" id="testimonial">
   <div class="container testimonial-block">
    <div class="intro-testimonial">
      <h2 class="text-center"><strong>Testimonials</strong></h2>
      <h4 class="text-center">Our customers love us! Read what they have to say below.</h4>
    </div>
    <div class="row people">
      <div class="col-md-6 col-lg-4 item">
        <div class="box">
            <p class="description">I have question: How come this app didn't exist before?!! Thank you Foodini, I'll use it again for sure!</p>
        </div>
        <div class="author"><img class="rounded-circle" src="https://avatars.githubusercontent.com/u/30535027?v=4">
            <h5 class="name">Greg</h5>
            <p class="title">Boardgame master</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-4 item">
        <div class="box">
            <p class="description">I have to say I'm very impressed by this new concept! It's good fun and super easy. I'll just have 1 word: W O W.</p>
        </div>
        <div class="author"><img class="rounded-circle" src="https://avatars.githubusercontent.com/u/81511893?v=4">
            <h5 class="name">Marco</h5>
            <p class="title">Mr Eurotrip</p>
        </div>
      </div>
      <div class="col-md-6 col-lg-4 item">
        <div class="box">
            <p class="description">Hey you guys should definitely try this out! As a true foodie I love discovering new cuisines and this app makes it all possible.</p>
        </div>
        <div class="author"><img class="rounded-circle" src="https://avatars.githubusercontent.com/u/87199265?v=4">
            <h5 class="name">Indira</h5>
            <p class="title">Wannabe software developer</p>
        </div>
      </div>
    </div>
    </div>
  </div>
</div>
    <%# <div id="container-reviews-landing">
      <h2 class="text-center">What our customers say</h2>
      <div class="cards-review">
        <div class="card-review">
          <img src="https://cdn.tasteatlas.com//images/dishes/eee2ad665ef54610b8aeb5a43ce74677.jpg?w=905&h=510" class="image-background">
          <p class="meal-delivered">Korean: Bulgogi</p>
          <div class="full-review">
            <div class="text-review">
              <h4 class="review-title">Oh Wow</h4>
              <p class="review-content">I have to say I'm very impressed by this new concept!</p>
            </div>
            <div class="user-rating">
              <h3 class="user-name">Marco</h3>
              <h3 class="rating">&#11088;&#11088;&#11088;&#11088;&#11088;</h3>
            </div>
          </div>
          <img src="https://avatars.githubusercontent.com/u/81511893?v=4" description="my face" class="profile">
        </div>
        <div class="card-review">
          <img src="https://cdn.tasteatlas.com//images/dishes/ad3ef1fb39eb42958e7462961951e45c.jpg?w=905&h=510" class="image-background">
          <p class="meal-delivered">Thai: Pad Thai</p>
          <div class="full-review">
            <div class="text-review">
              <h4 class="review-title">Loved the experience</h4>
              <p class="review-content">Hey you guys should definitely try this out!</p>
            </div>
            <div class="user-rating">
              <h3 class="user-name">Indira</h3>
              <h3 class="rating">&#11088;&#11088;&#11088;&#11088;&#11088;</h3>
            </div>
          </div>
          <img src="https://avatars.githubusercontent.com/u/87199265?v=4" description="my face" class="profile">
        </div>
        <div class="card-review">
          <img src="https://cdn.tasteatlas.com//Images/Dishes/bc0a3be4164b484ea01512c3ab6d4467.jpg?w=905&h=510" class="image-background">
          <p class="meal-delivered">Egyptian: Kushari</p>
          <div class="full-review">
            <div class="text-review">
              <h4 class="review-title">Thank you Foodini!</h4>
              <p class="review-content">I have question: How come this app didn't exist before?!!</p>
            </div>
            <div class="user-rating">
              <h3 class="user-name">Greg</h3>
              <h3 class="rating">&#11088;&#11088;&#11088;&#11088;&#11088;</h3>
            </div>
          </div>
          <img src="https://avatars.githubusercontent.com/u/30535027?v=4" description="my face" class="profile">
        </div>
      </div>
    </div> %>
  <%# </div> %>